"""added relationships to author blog, blog_image and email_list tables

Revision ID: 0c74a19961cc
Revises: 19a4077929f1
Create Date: 2023-10-30 15:54:42.314619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c74a19961cc'
down_revision = '19a4077929f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blod_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['blod_id'])
        batch_op.create_foreign_key(None, 'blogs', ['blod_id'], ['id'])

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['author_id'])
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('blog_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('blod_id')

    # ### end Alembic commands ###
