"""update names author blog, blog_image and email_list tables

Revision ID: 19a4077929f1
Revises: bd48dfcaa3e4
Create Date: 2023-10-30 15:41:57.447628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a4077929f1'
down_revision = 'bd48dfcaa3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=False))
        batch_op.drop_column('phone_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
