"""checker update

Revision ID: 694b446dfdd0
Revises: d207aa917375
Create Date: 2023-10-30 18:52:36.292234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694b446dfdd0'
down_revision = 'd207aa917375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_image', sa.String(), nullable=False))
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('feature_image')

    # ### end Alembic commands ###
