"""feat: addition of a new column in emaillist table to confirm if it's from virgros or not

Revision ID: f4674a9dc644
Revises: 694b446dfdd0
Create Date: 2023-12-20 15:12:23.397178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4674a9dc644'
down_revision = '694b446dfdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vivirgros', sa.Boolean(), nullable=True))
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_lists', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_vivirgros')

    # ### end Alembic commands ###
